name: anr_saver
description: "ANR Saver - Your Ultimate Video Saver"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.3.0+3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  device_preview: ^1.2.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  video_player: ^2.9.5
  dartz: ^0.10.1
  path_provider: ^2.1.4
  path: ^1.9.0
  gal: ^2.3.0
  video_thumbnail: ^0.5.3
  permission_handler: ^11.3.1
  get_it: ^7.7.0
  dio: ^5.5.0+1
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  chewie: ^1.8.3
  adaptive_theme: ^3.6.0
  bloc: ^8.1.4
  share_plus: ^7.2.2
  device_info_plus: ^10.1.0
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.1
  open_file: ^3.5.10
  android_intent_plus: ^5.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/android/mipmap-xxxhdpi/ic_launcher.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/launcher/android/mipmap-xxxhdpi/ic_launcher.png"
    background_color: "#2196F3"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/launcher/android/mipmap-xxxhdpi/ic_launcher.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher/
    - assets/splash/
    - assets/donate/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
